cappseq_normal_workflow:
  refgenome: "__UPDATE__"  # Should contain BWA indicies and samtools fai index in the same directory
  captureregions: "__UPDATE__"
  captureregionsil: "__UPDATE__"  # Picard Interval List

  # Input and output
  samplefile: "config/samplelist.tsv"
  baseoutdir: "__UPDATE__"

  readgroup:
    centre: "Genome_Quebec"
    platformunit: "ILLUMINA"
    platformmodel: "NOVASEQ"
    description: "CAPPSeq of normal samples"

  # Threads
  fastp_threads: 4
  bwa_threads: 16

  multiqc_config: "config/multiqc_config.yaml"